<script lang="ts" setup>
import { XCircle } from 'lucide-vue-next'
import TwoFactorAuth from '../auth/TwoFactorAuth.vue'
import { dateToTimestamp } from '@/utils'

const toast = useToast()
const { updateProfile } = useProfileStore()

const shouldShowDialog = computed(() => {
  const userCreatedAt = dateToTimestamp(useAuthStore().user?.createdAt)
  const userUpdatedAt = dateToTimestamp(useAuthStore().user?.updatedAt)
  return userCreatedAt === userUpdatedAt
})
const showDialog = ref(false)
const formData = reactive({
  privacy: useAuthStore().user?.pub ? 'public' : 'private'
})

const openDialog = () => {
  showDialog.value = true
}

const closeDialog = () => {
  showDialog.value = false
}

async function updatePrivacy() {
  try {
    await updateProfile({ pub: formData.privacy === 'public' ? true : false })
    toast.success('Profile visibility updated successfully')
  } catch (error: any) {
    toast.error(error.message)
  }
}

watch(
  () => useAuthStore().user?.pub,
  (value) => {
    formData.privacy = value ? 'public' : 'private'
  }
)

onMounted(() => {
  if (shouldShowDialog.value) openDialog()
})
</script>
<template>
  <slot :openDialog="openDialog" :closeDialog="closeDialog" />
  <Dialog v-model="showDialog">
    <div class="account-settings-container">
      <div class="account-settings">
        <div class="account-settings__sidenav">
          <div class="account-settings__sidenav__content">
            <h2 class="account-settings__sidenav__title">User Settings</h2>

            <ul class="account-settings__sidenav__list">
              <li class="account-settings__sidenav__list__item active">My Account</li>
            </ul>
          </div>
        </div>

        <div class="account-settings__main">
          <div class="account-settings__main__content">
            <div class="account-settings__main__header">
              <h2 class="account-settings__main__header__title">My Account</h2>
              <Button @click="closeDialog" class="account-settings__main__header__close">
                <XCircle />
                <span class="visually-hidden">Close</span>
              </Button>
            </div>
            <ProfileSettings />
            <div class="account-settings__main__settings">
              <ul class="account-settings__main__settings__list">
                <li class="account-settings__main__settings__list__item">
                  <h2>Profile Visibility</h2>
                  <p>
                    Choose who can see your profile information. You can choose to make your profile
                    visible to everyone, only your friends.
                  </p>

                  <div class="account-settings__main__settings__list__item__select">
                    <select v-model="formData.privacy" @change="updatePrivacy">
                      <option value="private">Private</option>
                      <option value="public">Public</option>
                    </select>
                  </div>
                </li>
                <li class="account-settings__main__settings__list__item active">
                  <h2>Authenticator App</h2>
                  <p>
                    Protect your account with an additional layer of security using the
                    Authenticator app. Once enabled, you will be prompted to enter a unique code
                    generated by the app during login.
                  </p>

                  <TwoFactorAuth />
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </Dialog>
</template>

<style lang="scss" scoped>
.account-settings-container {
  @apply flex items-center justify-center text-gray-200;
  @apply w-full h-full;
  @apply bg-[#313338];
}
.account-settings {
  @apply h-full w-full relative overflow-y-auto;
  @apply grid grid-cols-2 gap-4;
  display: grid;
  grid-template-columns: 2fr 4fr;

  &__sidenav {
    @apply flex justify-end px-4 py-14 sticky top-28;
    @apply bg-[#2B2D31];

    &__content {
      @apply flex flex-col;
    }

    &__title {
      @apply text-xs font-bold text-gray-500 uppercase px-2;
    }

    &__list {
      @apply flex flex-col mt-2;
      @apply space-y-2 w-[180px];

      &__item {
        @apply text-gray-400 text-base px-2.5 py-1 flex items-center;
        @apply hover:text-gray-200 hover:bg-[#404248] rounded-sm;
        @apply cursor-pointer;

        &.active {
          @apply text-gray-200 bg-[#404248];
        }
      }
    }
  }

  &__main {
    @apply flex flex-col pl-4 py-10;
    @apply bg-[#313338];

    &__content {
      @apply flex flex-col;
      @apply max-w-[700px] relative;
    }

    &__header {
      @apply flex items-center justify-between;
      @apply pb-4;

      &__title {
        @apply text-xl font-bold text-gray-400;
      }

      &__close {
        @apply w-[35px] h-[35px] rounded-full flex items-center justify-center opacity-50;
        @apply cursor-pointer;
        @apply transition-all duration-200;

        &:hover {
          @apply opacity-80;
        }

        svg {
          @apply w-[35px] h-[35px];
        }
      }
    }

    &__settings {
      @apply flex flex-col border-t border-gray-500 py-6 mt-6;
      @apply space-y-4;
      @apply text-gray-400;

      &__list {
        @apply flex flex-col space-y-5;
        @apply text-gray-400;

        &__item {
          @apply flex flex-col space-y-2;

          h2 {
            @apply text-lg font-bold;
          }

          p {
            @apply text-sm;
          }

          &__select {
            @apply w-[200px] h-[40px] relative;

            select {
              @apply w-full h-full bg-[#5765F2] text-gray-200 px-2 py-1 rounded-sm border border-transparent focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent;
            }
          }
        }
      }
    }
  }
}
</style>
